### ISSUE TITLE
Make this runnable out of the box

### ISSUE THREAD

**Issue by mogambro** [Lemonzyy/terrain-generation#1]
Hey there!

due to the dependency:

`fast-surface-nets = { path = "../fast-surface-nets-rs" }`

this cannot run out of the box.

Are you interested in making it so that one can check out the repo and just run it?

I am very much interested in using fast-surface-nets together with bevy myself and this looks like a very nice base :) (thanks for letting me have a look! :))

**Comment by Lemonzyy** [comment]
Hello!

I will update this later today, it's just a fast-surface-nets fix to work with the last version of glam.

Please also note that this is not a terrain generator for the moment since I am currently testing with a SDF that is much simpler to evaluate (infinite repetition of spheres).
